version: '3.6'
services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: always
    hostname: ${NEXUS_HOST}
    ports:
      - "${NEXUS_PORT}:8081"
    volumes:
      - ${NEXUS_NFS_DATA}:/nexus/data
      - ${NEXUS_SSL_CERT_PATH}:/etc/ssl/certs/nexus.crt:ro
      - ${NEXUS_SSL_KEY_PATH}:/etc/ssl/private/nexus.key:ro
    environment:
      - NEXUS_SECURITY_RANDOMPASSWORD=false
      - NEXUS_ADMIN_USER=${NEXUS_ADMIN_USER}
      - NEXUS_ADMIN_PASSWORD=${NEXUS_ADMIN_PASSWORD}
