apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-application-controller
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-application-controller
  template:
    metadata:
      labels:
        app: argocd-application-controller
    spec:
      containers:
      - name: application-controller
        image: quay.io/argoproj/argocd-application-controller:v2.11.0
        ports:
        - containerPort: 8082
